-- 들어올 때는 중성화 x, 나갈 때는 중성화
-- ID, 생물 종, 이름 조회
-- ID 순으로 조회
WITH ANIMAL_INTACT AS(
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
)
SELECT
	O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME 
FROM ANIMAL_OUTS AS O
JOIN ANIMAL_INTACT AS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME LIKE 'Neutered%' OR O.SEX_UPON_OUTCOME LIKE 'Spayed%'
ORDER BY 1;