-- 상반기 아이스크림 총주문량이 3,000보다 높으면서 (FIRST_HALF.TOTAL_ORDER)
-- 아이스크림의 주 성분이 과일인 아이스크림의 맛 (ICECREAM_INFO.INGREDIENT_TYPE)
-- 출력 FLAVOR, 총주문량 내림차순
SELECT
    F.FLAVOR
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;